#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MenuDriver_Eggpawn

#include "Basic.hpp"


namespace SDK::Params
{

// Function ABP_MenuDriver_Eggpawn.ABP_MenuDriver_Eggpawn_C.ExecuteUbergraph_ABP_MenuDriver_Eggpawn
// 0x0004 (0x0004 - 0x0000)
struct ABP_MenuDriver_Eggpawn_C_ExecuteUbergraph_ABP_MenuDriver_Eggpawn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ABP_MenuDriver_Eggpawn_C_ExecuteUbergraph_ABP_MenuDriver_Eggpawn;

}

