#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Signage

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Signage.BP_Signage_C
// 0x0010 (0x0318 - 0x0308)
class ABP_Signage_C final : public AFestaSignage
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveTick(float DeltaSeconds);
	void ExecuteUbergraph_BP_Signage(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Signage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Signage_C")
	}
	static class ABP_Signage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Signage_C>();
	}
};
DUMPER7_ASSERTS_ABP_Signage_C;

}

