#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_MenuStatePatyRace

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPC_MenuStatePatyRace.BPC_MenuStatePatyRace_C.ExecuteUbergraph_BPC_MenuStatePatyRace
// 0x0008 (0x0008 - 0x0000)
struct BPC_MenuStatePatyRace_C_ExecuteUbergraph_BPC_MenuStatePatyRace final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_InDeltaTime;                          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_MenuStatePatyRace_C_ExecuteUbergraph_BPC_MenuStatePatyRace;

// Function BPC_MenuStatePatyRace.BPC_MenuStatePatyRace_C.OnUpdateState
// 0x0004 (0x0004 - 0x0000)
struct BPC_MenuStatePatyRace_C_OnUpdateState final
{
public:
	float                                         InDeltaTime;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_MenuStatePatyRace_C_OnUpdateState;

}

