#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_LegendCompeNoticeEventEnd

#include "Basic.hpp"

#include "UnionUI_structs.hpp"
#include "UNION_structs.hpp"
#include "UNION_classes.hpp"
#include "UnionSystem_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_LegendCompeNoticeEventEnd.BPC_LegendCompeNoticeEventEnd_C
// 0x00B0 (0x01D8 - 0x0128)
class UBPC_LegendCompeNoticeEventEnd_C final : public UNoticeEventEndState
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0128(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_EventEndInfo_CMN_window_C*         EventEndInfo;                                      // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         EndEventID;                                        // 0x0138(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              EventEndBG;                                        // 0x0140(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class FText                                   EventName;                                         // 0x0168(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          DebugMode;                                         // 0x0178(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FRewardGetWindowParam>          RewardParamArray;                                  // 0x0180(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UWBP_ItemGet_Window_C*                  RewardDialog;                                      // 0x0190(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBPC_PreNotice_C*                       BPC_Pre_Notice;                                    // 0x0198(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLegendCompeRewardResultData           ResultData;                                        // 0x01A0(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void CreateRewardParamArray();
	void EventEndInfoWidget_Close();
	void GetBPC_PreNotice(class AActor* OwnerSequence_0, class UBPC_PreNotice_C** BPC_PreNotice);
	void GetFestaIdValue(int32* festaId);
	void Set_Footer_Visibility(bool IsVisible);
	void OnFinishedFade(EUnionUIFadeDirection FadeDirection);
	void NoReward();
	void OnSaveComplete(ESaveDataStatus Status);
	void StartClaimRankingRewards();
	void OnClosed_EventEndWidget();
	void OnClosed_ItemGet();
	void OnExitState();
	void OnInitState();
	void ExecuteUbergraph_BPC_LegendCompeNoticeEventEnd(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPC_LegendCompeNoticeEventEnd_C">();
	}
	static class UBPC_LegendCompeNoticeEventEnd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_LegendCompeNoticeEventEnd_C>();
	}
};
static_assert(alignof(UBPC_LegendCompeNoticeEventEnd_C) == 0x000008, "Wrong alignment on UBPC_LegendCompeNoticeEventEnd_C");
static_assert(sizeof(UBPC_LegendCompeNoticeEventEnd_C) == 0x0001D8, "Wrong size on UBPC_LegendCompeNoticeEventEnd_C");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, UberGraphFrame) == 0x000128, "Member 'UBPC_LegendCompeNoticeEventEnd_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, EventEndInfo) == 0x000130, "Member 'UBPC_LegendCompeNoticeEventEnd_C::EventEndInfo' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, EndEventID) == 0x000138, "Member 'UBPC_LegendCompeNoticeEventEnd_C::EndEventID' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, EventEndBG) == 0x000140, "Member 'UBPC_LegendCompeNoticeEventEnd_C::EventEndBG' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, EventName) == 0x000168, "Member 'UBPC_LegendCompeNoticeEventEnd_C::EventName' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, DebugMode) == 0x000178, "Member 'UBPC_LegendCompeNoticeEventEnd_C::DebugMode' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, RewardParamArray) == 0x000180, "Member 'UBPC_LegendCompeNoticeEventEnd_C::RewardParamArray' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, RewardDialog) == 0x000190, "Member 'UBPC_LegendCompeNoticeEventEnd_C::RewardDialog' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, BPC_Pre_Notice) == 0x000198, "Member 'UBPC_LegendCompeNoticeEventEnd_C::BPC_Pre_Notice' has a wrong offset!");
static_assert(offsetof(UBPC_LegendCompeNoticeEventEnd_C, ResultData) == 0x0001A0, "Member 'UBPC_LegendCompeNoticeEventEnd_C::ResultData' has a wrong offset!");

}

