#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_MenuSubStateSelectClass

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"
#include "UNION_structs.hpp"
#include "UNION_classes.hpp"
#include "Engine_structs.hpp"
#include "UnionUI_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_MenuSubStateSelectClass.BPC_MenuSubStateSelectClass_C
// 0x0088 (0x01B0 - 0x0128)
class UBPC_MenuSubStateSelectClass_C final : public UMenuSequenceSubStateBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0128(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_GrandPrixSequence_C*                OwnerGrandPrixSequence;                            // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   SelectClassClass;                                  // 0x0138(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UWBP_ClassSelect_C*                     SelectClass;                                       // 0x0160(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          bCaptureUpdate;                                    // 0x0168(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftClassPtr<class UClass>                   CourseSelectWidgetClassRef;                        // 0x0170(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          bFirstFocus;                                       // 0x0198(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bBackToCourseSelect;                               // 0x0199(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19A[0x6];                                      // 0x019A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMenuInputRecieveObject*                SubInputReciever;                                  // 0x01A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bRightShoulderPressed;                             // 0x01A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bLeftShoulderPressed;                              // 0x01A9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bStartPressed;                                     // 0x01AA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DestroyPlayer();
	void GetLastStateIsClassSelect(bool* LClassSelect);
	void UnbindAllEvents();
	void ConvertClassIdToIndex(ESpeedClassId ID, int32* Index_0);
	void ConvertIndexToClassId(int32 Index_0, EMenuSpeedClassId* MenuSpeedClass);
	void OnLoaded_34F2760D430D7D602227CAA2E60109C4(TSubclassOf<class UObject> Loaded);
	void OnLoaded_C245C939437FB5BD9D84E8966E301E25(TSubclassOf<class UObject> Loaded);
	void OnLeftShoulderPressedEvent_Event(class UObject* Object);
	void OnLeftShoulderReleasedEvent_Event(class UObject* Object);
	void ShoulderButtonCheck();
	void _OnSpecialPressedEvent_Event(class UObject* Object);
	void CustomEvent_0(class UObject* Object);
	void OnRightShoulderPressedEvent_Event(class UObject* Object);
	void CloseSubCommand();
	void OnRightShoulderReleasedEvent_Event(class UObject* Object);
	void StartSelectClassState();
	void OnClassSelectIn();
	void OnDecideClassSelectScene(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void OnCancel(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void OnUISceneFocusEvent_Event(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void OnOutAnimFinished();
	void OnInitState();
	void OnUpdateState(float InDeltaTime);
	void OnExitState();
	void OnNextSequence();
	void OnPrevSequence();
	void InitSubCommand();
	void UIFadeWidget_OnFinishedFade(EUnionUIFadeDirection FadeDirection);
	void OnOutFinished_PrevSequence();
	void ExecuteUbergraph_BPC_MenuSubStateSelectClass(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_MenuSubStateSelectClass_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_MenuSubStateSelectClass_C")
	}
	static class UBPC_MenuSubStateSelectClass_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_MenuSubStateSelectClass_C>();
	}
};
DUMPER7_ASSERTS_UBPC_MenuSubStateSelectClass_C;

}

