#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_stg0010

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function SL_stg0010.SL_stg0010_C.SetPostProcessEnabled
// 0x0001 (0x0001 - 0x0000)
struct SL_stg0010_C_SetPostProcessEnabled final
{
public:
	bool                                          bEnabled;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_SetPostProcessEnabled;

// Function SL_stg0010.SL_stg0010_C.SetPostProcessEnable
// 0x0001 (0x0001 - 0x0000)
struct SL_stg0010_C_SetPostProcessEnable final
{
public:
	bool                                          bEnable;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_SetPostProcessEnable;

// Function SL_stg0010.SL_stg0010_C.SetLightingEnable
// 0x0001 (0x0001 - 0x0000)
struct SL_stg0010_C_SetLightingEnable final
{
public:
	bool                                          bEnable;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_SetLightingEnable;

// Function SL_stg0010.SL_stg0010_C.SetLightActorHiddenInGame
// 0x0001 (0x0001 - 0x0000)
struct SL_stg0010_C_SetLightActorHiddenInGame final
{
public:
	bool                                          NewHidden;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_SetLightActorHiddenInGame;

// Function SL_stg0010.SL_stg0010_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct SL_stg0010_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_ReceiveEndPlay;

// Function SL_stg0010.SL_stg0010_C.GetPartyRaceSceneCamera
// 0x0008 (0x0008 - 0x0000)
struct SL_stg0010_C_GetPartyRaceSceneCamera final
{
public:
	class ACameraActor*                           OutCamera;                                         // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetPartyRaceSceneCamera;

// Function SL_stg0010.SL_stg0010_C.GetOrbotActor
// 0x0008 (0x0008 - 0x0000)
struct SL_stg0010_C_GetOrbotActor final
{
public:
	class ASkeletalMeshActor*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetOrbotActor;

// Function SL_stg0010.SL_stg0010_C.GetFestaVoltageActors
// 0x0010 (0x0010 - 0x0000)
struct SL_stg0010_C_GetFestaVoltageActors final
{
public:
	TArray<class AActor*>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetFestaVoltageActors;

// Function SL_stg0010.SL_stg0010_C.GetFestaGroupPlates
// 0x0010 (0x0010 - 0x0000)
struct SL_stg0010_C_GetFestaGroupPlates final
{
public:
	TArray<class UStaticMeshComponent*>           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, ContainsInstancedReference)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetFestaGroupPlates;

// Function SL_stg0010.SL_stg0010_C.GetDodonpaEventSceneCamera
// 0x0008 (0x0008 - 0x0000)
struct SL_stg0010_C_GetDodonpaEventSceneCamera final
{
public:
	class ACameraActor*                           newParam;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetDodonpaEventSceneCamera;

// Function SL_stg0010.SL_stg0010_C.GetDodonpaActor
// 0x0008 (0x0008 - 0x0000)
struct SL_stg0010_C_GetDodonpaActor final
{
public:
	class ASkeletalMeshActor*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetDodonpaActor;

// Function SL_stg0010.SL_stg0010_C.GetCubotActor
// 0x0008 (0x0008 - 0x0000)
struct SL_stg0010_C_GetCubotActor final
{
public:
	class ASkeletalMeshActor*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetCubotActor;

// Function SL_stg0010.SL_stg0010_C.GetCameraActor
// 0x0008 (0x0008 - 0x0000)
struct SL_stg0010_C_GetCameraActor final
{
public:
	class ACameraActor*                           ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_GetCameraActor;

// Function SL_stg0010.SL_stg0010_C.ExecuteUbergraph_SL_stg0010
// 0x0090 (0x0090 - 0x0000)
struct SL_stg0010_C_ExecuteUbergraph_SL_stg0010 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_NewHidden;                            // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bEnabled;                             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bEnable_1;                            // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bEnable;                              // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B[0x5];                                        // 0x000B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0010(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Signage_C*                          CallFunc_FinishSpawningActor_ReturnValue;          // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_stg0010_C_ExecuteUbergraph_SL_stg0010;

}

