#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_stg0010

#include "Basic.hpp"

#include "SL_stg0010_classes.hpp"
#include "SL_stg0010_parameters.hpp"


namespace SDK
{

// Function SL_stg0010.SL_stg0010_C.SetPostProcessEnabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnabled                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::SetPostProcessEnabled(bool bEnabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "SetPostProcessEnabled");

	Params::SL_stg0010_C_SetPostProcessEnabled Parms{};

	Parms.bEnabled = bEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SL_stg0010.SL_stg0010_C.SetPostProcessEnable
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnable                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::SetPostProcessEnable(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "SetPostProcessEnable");

	Params::SL_stg0010_C_SetPostProcessEnable Parms{};

	Parms.bEnable = bEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SL_stg0010.SL_stg0010_C.SetLightingEnable
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnable                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::SetLightingEnable(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "SetLightingEnable");

	Params::SL_stg0010_C_SetLightingEnable Parms{};

	Parms.bEnable = bEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SL_stg0010.SL_stg0010_C.SetLightActorHiddenInGame
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewHidden                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::SetLightActorHiddenInGame(bool NewHidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "SetLightActorHiddenInGame");

	Params::SL_stg0010_C_SetLightActorHiddenInGame Parms{};

	Parms.NewHidden = NewHidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SL_stg0010.SL_stg0010_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "ReceiveEndPlay");

	Params::SL_stg0010_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SL_stg0010.SL_stg0010_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASL_stg0010_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SL_stg0010.SL_stg0010_C.GetPartyRaceSceneCamera
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACameraActor**                    OutCamera                                              (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::GetPartyRaceSceneCamera(class ACameraActor** OutCamera)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetPartyRaceSceneCamera");

	Params::SL_stg0010_C_GetPartyRaceSceneCamera Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutCamera != nullptr)
		*OutCamera = Parms.OutCamera;
}


// Function SL_stg0010.SL_stg0010_C.GetOrbotActor
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkeletalMeshActor*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class ASkeletalMeshActor* ASL_stg0010_C::GetOrbotActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetOrbotActor");

	Params::SL_stg0010_C_GetOrbotActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SL_stg0010.SL_stg0010_C.GetFestaVoltageActors
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class AActor*>                   ReturnValue                                            (Parm, OutParm, ReturnParm)

TArray<class AActor*> ASL_stg0010_C::GetFestaVoltageActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetFestaVoltageActors");

	Params::SL_stg0010_C_GetFestaVoltageActors Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SL_stg0010.SL_stg0010_C.GetFestaGroupPlates
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UStaticMeshComponent*>     ReturnValue                                            (Parm, OutParm, ReturnParm, ContainsInstancedReference)

TArray<class UStaticMeshComponent*> ASL_stg0010_C::GetFestaGroupPlates()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetFestaGroupPlates");

	Params::SL_stg0010_C_GetFestaGroupPlates Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SL_stg0010.SL_stg0010_C.GetDodonpaEventSceneCamera
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACameraActor**                    newParam                                               (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::GetDodonpaEventSceneCamera(class ACameraActor** newParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetDodonpaEventSceneCamera");

	Params::SL_stg0010_C_GetDodonpaEventSceneCamera Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (newParam != nullptr)
		*newParam = Parms.newParam;
}


// Function SL_stg0010.SL_stg0010_C.GetDodonpaActor
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkeletalMeshActor*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class ASkeletalMeshActor* ASL_stg0010_C::GetDodonpaActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetDodonpaActor");

	Params::SL_stg0010_C_GetDodonpaActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SL_stg0010.SL_stg0010_C.GetCubotActor
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkeletalMeshActor*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class ASkeletalMeshActor* ASL_stg0010_C::GetCubotActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetCubotActor");

	Params::SL_stg0010_C_GetCubotActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SL_stg0010.SL_stg0010_C.GetCameraActor
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACameraActor*                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class ACameraActor* ASL_stg0010_C::GetCameraActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "GetCameraActor");

	Params::SL_stg0010_C_GetCameraActor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SL_stg0010.SL_stg0010_C.ExecuteUbergraph_SL_stg0010
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASL_stg0010_C::ExecuteUbergraph_SL_stg0010(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_stg0010_C", "ExecuteUbergraph_SL_stg0010");

	Params::SL_stg0010_C_ExecuteUbergraph_SL_stg0010 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

