#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_stg0010

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass SL_stg0010.SL_stg0010_C
// 0x0070 (0x0310 - 0x02A0)
class ASL_stg0010_C final : public AMenuLightingLevel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_Signage_C*                          Signage;                                           // 0x02A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AExponentialHeightFog*                  ExponentialHeightFog_1_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ADirectionalLight*                      LightSource_0_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ALightmassImportanceVolume*             LightmassImportanceVolume_1_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APostProcessVolume*                     PostProcessVolume_1_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASkyLight*                              SkyLight_1_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APointLight*                            PointLight_1_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APointLight*                            PointLight_0_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APointLight*                            PointLight_2_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APointLight*                            PointLight_3_ExecuteUbergraph_SL_stg0010_RefProperty; // 0x02F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       CineCameraActor_1_GetPartyRaceSceneCamera_MERGED_RefProperty; // 0x02F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       CineCameraActor_0_GetDodonpaEventSceneCamera_MERGED_RefProperty; // 0x0300(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       CineCameraActor_1_GetCameraActor_MERGED_RefProperty; // 0x0308(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void SetPostProcessEnabled(bool bEnabled);
	void SetPostProcessEnable(bool bEnable);
	void SetLightingEnable(bool bEnable);
	void SetLightActorHiddenInGame(bool NewHidden);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveBeginPlay();
	void GetPartyRaceSceneCamera(class ACameraActor** OutCamera);
	class ASkeletalMeshActor* GetOrbotActor();
	TArray<class AActor*> GetFestaVoltageActors();
	TArray<class UStaticMeshComponent*> GetFestaGroupPlates();
	void GetDodonpaEventSceneCamera(class ACameraActor** newParam);
	class ASkeletalMeshActor* GetDodonpaActor();
	class ASkeletalMeshActor* GetCubotActor();
	class ACameraActor* GetCameraActor();
	void ExecuteUbergraph_SL_stg0010(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SL_stg0010_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SL_stg0010_C")
	}
	static class ASL_stg0010_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASL_stg0010_C>();
	}
};
DUMPER7_ASSERTS_ASL_stg0010_C;

}

