#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Window_Sub_Option

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionUI_classes.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Window_Sub_Option.WBP_Window_Sub_Option_C
// 0x0068 (0x04E8 - 0x0480)
class UWBP_Window_Sub_Option_C final : public UUnionUIButtonBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0480(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Select_Loop;                                       // 0x0488(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Active_Loop;                                       // 0x0490(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 DSP_TSR;                                           // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUnionUIButton*                         MouseInteraction;                                  // 0x04A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PAT_OptionPict;                                    // 0x04A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PAT_OptionToggleBtn;                               // 0x04B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TXT_OptionType;                                    // 0x04B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         Index_0;                                           // 0x04C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          Enable;                                            // 0x04C4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_4C5[0x3];                                      // 0x04C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   TypeText;                                          // 0x04C8(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)
	class AMenuPlayerController*                  OwnerPlayerController;                             // 0x04D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LastFocusAnim;                                     // 0x04E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void SetupTSR();
	void SetupIcon();
	void SetToggleBtn(bool bEnable);
	void SetText(const class FText& TypeText_0);
	void PreConstruct(bool IsDesignTime);
	void PlaySEFocus();
	void PlaySEDecide();
	void PlayAnimationLoop();
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	void OnFocusLostImpl();
	void OnFocusLost(const struct FFocusEvent& InFocusEvent);
	void OnFocusImpl();
	void OnBackKeyPressed();
	void OnAcceptKeyPressed();
	class UWidget* NavigationRight(EUINavigation Navigation_0);
	class UWidget* NavigationLeft(EUINavigation Navigation_0);
	void ExecuteUbergraph_WBP_Window_Sub_Option(int32 EntryPoint);
	void Decide();
	void Construct();
	void Cancel();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Window_Sub_Option_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Window_Sub_Option_C")
	}
	static class UWBP_Window_Sub_Option_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Window_Sub_Option_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Window_Sub_Option_C;

}

