#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CharaMachineSelect_Sub_TypeBtn

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_CharaMachineSelect_Sub_TypeBtn.WBP_CharaMachineSelect_Sub_TypeBtn_C
// 0x0018 (0x0328 - 0x0310)
class UWBP_CharaMachineSelect_Sub_TypeBtn_C final : public UCharaMachineSelectPartsMachineType
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0310(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TMulticastInlineDelegate<void()>              OnClick;                                           // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_WBP_CharaMachineSelect_Sub_TypeBtn(int32 EntryPoint);
	void BndEvt__WBP_CharaMachineSelect_Sub_TypeBtn_WBP_FooterShortCut_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CharaMachineSelect_Sub_TypeBtn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CharaMachineSelect_Sub_TypeBtn_C")
	}
	static class UWBP_CharaMachineSelect_Sub_TypeBtn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CharaMachineSelect_Sub_TypeBtn_C>();
	}
};
DUMPER7_ASSERTS_UWBP_CharaMachineSelect_Sub_TypeBtn_C;

}

