#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCharaSelect_M1

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MachineCharaSelect_M1.WBP_MachineCharaSelect_M1_C
// 0x0028 (0x03A8 - 0x0380)
class UWBP_MachineCharaSelect_M1_C final : public UCharaMachineSelectsBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       M1_Out;                                            // 0x0388(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       M1_Loop;                                           // 0x0390(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       M1_In;                                             // 0x0398(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWBP_MachineCharaSelect_M1_P1_C*        WBP_MachineCharaSelect_M1_P1;                      // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void WidgetAnimationEvt_M1_In_K2Node_WidgetAnimationEvent_0();
	void PlaySoundError();
	void OnPlayAnimationOut();
	void OnPlayAnimationNormal();
	void OnPlayAnimationIn();
	void OnInit();
	void ExecuteUbergraph_WBP_MachineCharaSelect_M1(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineCharaSelect_M1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineCharaSelect_M1_C")
	}
	static class UWBP_MachineCharaSelect_M1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineCharaSelect_M1_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineCharaSelect_M1_C;

}

