#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter.WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C.ExecuteUbergraph_WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter
// 0x0004 (0x0004 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C_ExecuteUbergraph_WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C_ExecuteUbergraph_WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter;

}

