#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCharaSelect_M1_P1

#include "Basic.hpp"

#include "UNION_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C
// 0x0028 (0x04C0 - 0x0498)
class UWBP_MachineCharaSelect_M1_P1_C final : public UCharaMachineSelectBase
{
public:
	class UWidgetAnimation*                       M1_CharaSelect_to_MachineSelect;                   // 0x0498(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       M1_Out;                                            // 0x04A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       M1_Loop;                                           // 0x04A8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       M1_In;                                             // 0x04B0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWindowCharaChange*                     WBP_Window_SkinWindow;                             // 0x04B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void PlayAnimOut();
	void PlayAnimMachineType();
	void PlayAnimLoop();
	void PlayAnimIn();
	void PlayAnimCharaSelect();
	void ColorWindowOverrideNavigationRule();

	class UWindowCharaChange* GetCharacterSkinWindow() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineCharaSelect_M1_P1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineCharaSelect_M1_P1_C")
	}
	static class UWBP_MachineCharaSelect_M1_P1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineCharaSelect_M1_P1_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineCharaSelect_M1_P1_C;

}

