#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CharaMachineSelect_Sub_TypeBtn

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CharaMachineSelect_Sub_TypeBtn.WBP_CharaMachineSelect_Sub_TypeBtn_C.ExecuteUbergraph_WBP_CharaMachineSelect_Sub_TypeBtn
// 0x0004 (0x0004 - 0x0000)
struct WBP_CharaMachineSelect_Sub_TypeBtn_C_ExecuteUbergraph_WBP_CharaMachineSelect_Sub_TypeBtn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CharaMachineSelect_Sub_TypeBtn_C_ExecuteUbergraph_WBP_CharaMachineSelect_Sub_TypeBtn;

}

