#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineSelect_Sub_PartsScrollBox_W

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"


namespace SDK::Params
{

// Function WBP_MachineSelect_Sub_PartsScrollBox_W.WBP_MachineSelect_Sub_PartsScrollBox_W_C.PlaySoundImpossible
// 0x0004 (0x0004 - 0x0000)
struct WBP_MachineSelect_Sub_PartsScrollBox_W_C_PlaySoundImpossible final
{
public:
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x0000(0x0004)()
};
DUMPER7_ASSERTS_WBP_MachineSelect_Sub_PartsScrollBox_W_C_PlaySoundImpossible;

// Function WBP_MachineSelect_Sub_PartsScrollBox_W.WBP_MachineSelect_Sub_PartsScrollBox_W_C.PlaySoundPossible
// 0x0004 (0x0004 - 0x0000)
struct WBP_MachineSelect_Sub_PartsScrollBox_W_C_PlaySoundPossible final
{
public:
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x0000(0x0004)()
};
DUMPER7_ASSERTS_WBP_MachineSelect_Sub_PartsScrollBox_W_C_PlaySoundPossible;

}

