#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CMN_ChancePop

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CMN_ChancePop.WBP_CMN_ChancePop_C.Set Chance Up Text
// 0x0020 (0x0020 - 0x0000)
struct WBP_CMN_ChancePop_C_Set_Chance_Up_Text final
{
public:
	class FText                                   InChanceUpText;                                    // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   InRatioText;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_CMN_ChancePop_C_Set_Chance_Up_Text;

}

