#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CMN_Nice

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CMN_Nice.WBP_CMN_Nice_C.ExecuteUbergraph_WBP_CMN_Nice
// 0x0004 (0x0004 - 0x0000)
struct WBP_CMN_Nice_C_ExecuteUbergraph_WBP_CMN_Nice final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_CMN_Nice_C_ExecuteUbergraph_WBP_CMN_Nice;

}

