#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Window_CharaChange

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"


namespace SDK::Params
{

// Function WBP_Window_CharaChange.WBP_Window_CharaChange_C.PlaySEOpen
// 0x0004 (0x0004 - 0x0000)
struct WBP_Window_CharaChange_C_PlaySEOpen final
{
public:
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x0000(0x0004)()
};
DUMPER7_ASSERTS_WBP_Window_CharaChange_C_PlaySEOpen;

// Function WBP_Window_CharaChange.WBP_Window_CharaChange_C.PlayAnimationOut
// 0x0008 (0x0008 - 0x0000)
struct WBP_Window_CharaChange_C_PlayAnimationOut final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_CharaChange_C_PlayAnimationOut;

// Function WBP_Window_CharaChange.WBP_Window_CharaChange_C.PlayAnimationLoop
// 0x0008 (0x0008 - 0x0000)
struct WBP_Window_CharaChange_C_PlayAnimationLoop final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_CharaChange_C_PlayAnimationLoop;

// Function WBP_Window_CharaChange.WBP_Window_CharaChange_C.PlayAnimationIn
// 0x0008 (0x0008 - 0x0000)
struct WBP_Window_CharaChange_C_PlayAnimationIn final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_CharaChange_C_PlayAnimationIn;

// Function WBP_Window_CharaChange.WBP_Window_CharaChange_C.ExecuteUbergraph_WBP_Window_CharaChange
// 0x0004 (0x0004 - 0x0000)
struct WBP_Window_CharaChange_C_ExecuteUbergraph_WBP_Window_CharaChange final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_CharaChange_C_ExecuteUbergraph_WBP_Window_CharaChange;

// Function WBP_Window_CharaChange.WBP_Window_CharaChange_C.IsOpen
// 0x0018 (0x0018 - 0x0000)
struct WBP_Window_CharaChange_C_IsOpen final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRenderOpacity_ReturnValue;             // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_B_ImplicitCast;         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_CharaChange_C_IsOpen;

}

