#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter.WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C
// 0x0008 (0x0310 - 0x0308)
class UWBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C final : public UMachinePartsCharaParameter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter(int32 EntryPoint);
	void BndEvt__WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_WBP_CharaMachineSelect_Sub_TypeBtn_K2Node_ComponentBoundEvent_0_OnClick__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C")
	}
	static class UWBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineCharaSelect_M1_P1_Sub_CharaParameter_C;

}

