#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Friend_Sub_LobbyInvitation

#include "Basic.hpp"

#include "UNION_structs.hpp"
#include "UNION_classes.hpp"
#include "Engine_structs.hpp"
#include "UnionUI_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Friend_Sub_LobbyInvitation.WBP_Friend_Sub_LobbyInvitation_C
// 0x00A8 (0x0598 - 0x04F0)
class UWBP_Friend_Sub_LobbyInvitation_C final : public UFriendListContentsWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_Friend_Sub_MyLobbyId_InfoText_C*   DSP_WBP_Friend_Sub_MyLobbyId_InfoText;             // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MyLobbyIdBase;                                     // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MyLobbyIdBase_1;                                   // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_0;                                       // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUnionUITextBlock*                      TXT_MyLobbyId;                                     // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Friend_SubMenu_Btn_C*              WBP_Friend_SubMenu_Btn_01;                         // 0x0520(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Friend_SubMenu_Btn_C*              WBP_Friend_SubMenu_Btn_02;                         // 0x0528(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UWBP_Friend_Sub_PlayerPlate_Small_C*> ItemWidgetArray;                              // 0x0530(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UFriendListNumberInputWidget*           NumberInputWidget;                                 // 0x0540(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EFriendListCommandType                        AttentionCommandType;                              // 0x0548(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_549[0x7];                                      // 0x0549(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIPopupWindowBase*                PopupWindow;                                       // 0x0550(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UWBP_Friend_Sub_PlayerPlate_Small_C*> ScrollBoxWidgetArray;                         // 0x0558(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class FText                                   CreateShotLobyyIdText;                             // 0x0568(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   DisplayShortLobbyIdText;                           // 0x0578(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   OutNumberInputText;                                // 0x0588(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void GetShortLobbyIdButtonText(class FText* OutText);
	void IsOnlyJoinPublicLobby(bool* bOutOnlyJoin);
	void IsOnlyJoinPrivateLobby(bool* bOutOnlyJoin);
	class UFriendListNumberInputWidget* GetNumberInputWidget();
	void Check_Lobby_Join_Attention(bool* bOutAttention);
	struct FEventReply OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent);
	class UScrollBox* GetScrollBoxWidget();
	void Construct();
	void OnListItemDecisionDown(class UUnionUIButtonBase* Button);
	void SetupListItemWidgetSingle(class UWBP_Friend_Sub_PlayerPlate_Small_C* InItemListWidget, const struct FFriendListPlayerInfo& InListPlayerInfo, int32 InButtonIndex);
	void OnListItemCancelDown(class UUnionUIButtonBase* Button);
	void FocusListItemWidget(bool bInPlayFocusSound);
	void OnNumberInputWidgetDecision(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void CreateNumberInputWidget();
	void OnUserSearchSuccess(const TArray<struct FCommon_UserSearchData>& InUserSearchData);
	void ExecuteAfterConfirmWidget(EFriendListCommandType CommandType, int32 InButtonIndex, bool bInCanceled);
	void OnButtonDecisionEvent(class UUnionUIButtonBase* Button);
	void OnLobbyIdButtonDecisionEvent(class UUnionUIButtonBase* Button);
	void SetOwnLobbyIdText(const class FString& InLobbyId, bool bInWaitDisplay);
	void SetupListItemWidget();
	void AddListItemWidgetByListItemIndex(int32 InListItemIndex);
	void SetButtonControlEnable(bool bInEnable);
	void SetButtonNavigation();
	void UpdateLobbyId(const class FString& InShortLobbyId, bool InRequestSuccess);
	void SetListItemWidgetInteractableState(bool bInEnable);
	void SetListItemWidgetButtonChangeableState(int32 InListItemIndex, bool bEnable);
	void SetWidgetFocus(class APlayerController* PlayerController, bool bInPlayFocusSound);
	void OnAttentionPopupWindowDecision(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void SetupAttentionPopupWindow(EFriendListCommandType InCommandType);
	void UpdateButtonSelectable();
	void OnLobbyIdSearchSuccess(const TArray<struct FCommon_UserSearchData>& InUserSearchData, const TArray<struct FLobbyId>& InLobbyIdData, ELobbyType InLobbyType);
	void SetContentsControlEnable(bool bInEnable);
	void ClearButtonNavigation();
	void SetButtonControlEnableSingle(class UWBP_Friend_SubMenu_Btn_C* InSubMenuButton, bool bInEnable);
	void OnDirectionChange(class UUnionUIButtonBase* Button, EUnionUIControlDir Dir);
	void DestroyNumberInputWidget();
	void ResetContentsWidgetFocus();
	void SetScrollBoxVisibility(ESlateVisibility Param);
	void Destruct();
	void SetupButton();
	void ExecuteUbergraph_WBP_Friend_Sub_LobbyInvitation(int32 EntryPoint);

	bool CheckButtonWidgetExist() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Friend_Sub_LobbyInvitation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Friend_Sub_LobbyInvitation_C")
	}
	static class UWBP_Friend_Sub_LobbyInvitation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Friend_Sub_LobbyInvitation_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Friend_Sub_LobbyInvitation_C;

}

