#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCharaSelect_M1_P1

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C.PlayAnimOut
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_C_PlayAnimOut final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_C_PlayAnimOut;

// Function WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C.PlayAnimMachineType
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_C_PlayAnimMachineType final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_C_PlayAnimMachineType;

// Function WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C.PlayAnimLoop
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_C_PlayAnimLoop final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_C_PlayAnimLoop;

// Function WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C.PlayAnimIn
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_C_PlayAnimIn final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_C_PlayAnimIn;

// Function WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C.PlayAnimCharaSelect
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_C_PlayAnimCharaSelect final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationReverse_ReturnValue;         // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_C_PlayAnimCharaSelect;

// Function WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C.ColorWindowOverrideNavigationRule
// 0x0018 (0x0018 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_C_ColorWindowOverrideNavigationRule final
{
public:
	class UMachineColorSelectWindow*              CallFunc_GetColorWindow_ReturnValue;               // 0x0000(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_MachineSelect_Sub_ColorWindow_C*   K2Node_DynamicCast_AsWBP_Machine_Select_Sub_Color_Window; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_C_ColorWindowOverrideNavigationRule;

// Function WBP_MachineCharaSelect_M1_P1.WBP_MachineCharaSelect_M1_P1_C.GetCharacterSkinWindow
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_P1_C_GetCharacterSkinWindow final
{
public:
	class UWindowCharaChange*                     ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_P1_C_GetCharacterSkinWindow;

}

