#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineSelect_Sub_PartsWindow

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MachineSelect_Sub_PartsWindow.WBP_MachineSelect_Sub_PartsWindow_C
// 0x0010 (0x0560 - 0x0550)
class UWBP_MachineSelect_Sub_PartsWindow_C final : public UMachinePartsSelectWindow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0550(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_MachineSelect_Sub_Ready_C*         WBP_MachineSelect_Sub_Ready;                       // 0x0558(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void PreConstruct(bool IsDesignTime);
	void ExecuteUbergraph_WBP_MachineSelect_Sub_PartsWindow(int32 EntryPoint);
	void Construct();

	class URewardDialog* OnCreateRewardDialog() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MachineSelect_Sub_PartsWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MachineSelect_Sub_PartsWindow_C")
	}
	static class UWBP_MachineSelect_Sub_PartsWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MachineSelect_Sub_PartsWindow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MachineSelect_Sub_PartsWindow_C;

}

