#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineSelect_Sub_Btn_OK

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_MachineSelect_Sub_Btn_OK.WBP_MachineSelect_Sub_Btn_OK_C.PlayAnimActiveToSelect
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineSelect_Sub_Btn_OK_C_PlayAnimActiveToSelect final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineSelect_Sub_Btn_OK_C_PlayAnimActiveToSelect;

// Function WBP_MachineSelect_Sub_Btn_OK.WBP_MachineSelect_Sub_Btn_OK_C.PlayAnimSelectToActive
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineSelect_Sub_Btn_OK_C_PlayAnimSelectToActive final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineSelect_Sub_Btn_OK_C_PlayAnimSelectToActive;

}

