#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_StatusInfo_Sub_NGGadjet

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_StatusInfo_Sub_NGGadjet.WBP_StatusInfo_Sub_NGGadjet_C.SetText
// 0x0010 (0x0010 - 0x0000)
struct WBP_StatusInfo_Sub_NGGadjet_C_SetText final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_StatusInfo_Sub_NGGadjet_C_SetText;

}

