#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MachineCharaSelect_M1

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"


namespace SDK::Params
{

// Function WBP_MachineCharaSelect_M1.WBP_MachineCharaSelect_M1_C.PlaySoundError
// 0x0004 (0x0004 - 0x0000)
struct WBP_MachineCharaSelect_M1_C_PlaySoundError final
{
public:
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x0000(0x0004)()
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_C_PlaySoundError;

// Function WBP_MachineCharaSelect_M1.WBP_MachineCharaSelect_M1_C.OnPlayAnimationOut
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_C_OnPlayAnimationOut final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_C_OnPlayAnimationOut;

// Function WBP_MachineCharaSelect_M1.WBP_MachineCharaSelect_M1_C.OnPlayAnimationNormal
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_C_OnPlayAnimationNormal final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_C_OnPlayAnimationNormal;

// Function WBP_MachineCharaSelect_M1.WBP_MachineCharaSelect_M1_C.OnPlayAnimationIn
// 0x0008 (0x0008 - 0x0000)
struct WBP_MachineCharaSelect_M1_C_OnPlayAnimationIn final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_C_OnPlayAnimationIn;

// Function WBP_MachineCharaSelect_M1.WBP_MachineCharaSelect_M1_C.OnInit
// 0x0010 (0x0010 - 0x0000)
struct WBP_MachineCharaSelect_M1_C_OnInit final
{
public:
	TArray<class UCharaMachineSelectBase*>        K2Node_MakeArray_Array;                            // 0x0000(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_C_OnInit;

// Function WBP_MachineCharaSelect_M1.WBP_MachineCharaSelect_M1_C.ExecuteUbergraph_WBP_MachineCharaSelect_M1
// 0x0004 (0x0004 - 0x0000)
struct WBP_MachineCharaSelect_M1_C_ExecuteUbergraph_WBP_MachineCharaSelect_M1 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_MachineCharaSelect_M1_C_ExecuteUbergraph_WBP_MachineCharaSelect_M1;

}

