#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Window_MachineOption

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Window_MachineOption.WBP_Window_MachineOption_C
// 0x0020 (0x0438 - 0x0418)
class UWBP_Window_MachineOption_C final : public UMachineOptionWindow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0418(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Option_Out;                                        // 0x0420(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Option_Loop;                                       // 0x0428(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Option_In;                                         // 0x0430(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void WidgetAnimationEvt_Option_Out_K2Node_WidgetAnimationEvent_1();
	void WidgetAnimationEvt_Option_In_K2Node_WidgetAnimationEvent_0();
	void SetupAssistHandle(bool IsFlag);
	void SetupAssistAutoAccel(bool IsFlag);
	void SetupAssistAerialTrick(bool IsFlag);
	void PreConstruct(bool IsDesignTime);
	void OnPlaySEAnim();
	void OnPlayAnimOut();
	void OnPlayAnimLoop();
	void OnPlayAnimIn();
	void ExecuteUbergraph_WBP_Window_MachineOption(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Window_MachineOption_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Window_MachineOption_C")
	}
	static class UWBP_Window_MachineOption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Window_MachineOption_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Window_MachineOption_C;

}

