#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CMN_Sub_ChancePop_Magnification

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_CMN_Sub_ChancePop_Magnification.WBP_CMN_Sub_ChancePop_Magnification_C.SetRatioText
// 0x0010 (0x0010 - 0x0000)
struct WBP_CMN_Sub_ChancePop_Magnification_C_SetRatioText final
{
public:
	class FText                                   InRatioText;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_CMN_Sub_ChancePop_Magnification_C_SetRatioText;

}

