#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Window_MachineOption

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"


namespace SDK::Params
{

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.SetupAssistHandle
// 0x0020 (0x0020 - 0x0000)
struct WBP_Window_MachineOption_C_SetupAssistHandle final
{
public:
	bool                                          IsFlag;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_GetHandleAssist_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_Window_Sub_Option_C*               K2Node_DynamicCast_AsWBP_Window_Sub_Option;        // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_SetupAssistHandle;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.SetupAssistAutoAccel
// 0x0020 (0x0020 - 0x0000)
struct WBP_Window_MachineOption_C_SetupAssistAutoAccel final
{
public:
	bool                                          IsFlag;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_GetAutoAccel_ReturnValue;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_Window_Sub_Option_C*               K2Node_DynamicCast_AsWBP_Window_Sub_Option;        // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_SetupAssistAutoAccel;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.SetupAssistAerialTrick
// 0x0020 (0x0020 - 0x0000)
struct WBP_Window_MachineOption_C_SetupAssistAerialTrick final
{
public:
	bool                                          IsFlag;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUIButtonBase*                     CallFunc_GetAerialTrickAssist_ReturnValue;         // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_Window_Sub_Option_C*               K2Node_DynamicCast_AsWBP_Window_Sub_Option;        // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_SetupAssistAerialTrick;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Window_MachineOption_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_PreConstruct;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.OnPlaySEAnim
// 0x0004 (0x0004 - 0x0000)
struct WBP_Window_MachineOption_C_OnPlaySEAnim final
{
public:
	struct FSoundHandle                           CallFunc_SoundPlay_ReturnValue;                    // 0x0000(0x0004)()
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_OnPlaySEAnim;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.OnPlayAnimOut
// 0x0008 (0x0008 - 0x0000)
struct WBP_Window_MachineOption_C_OnPlayAnimOut final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_OnPlayAnimOut;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.OnPlayAnimLoop
// 0x0008 (0x0008 - 0x0000)
struct WBP_Window_MachineOption_C_OnPlayAnimLoop final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_OnPlayAnimLoop;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.OnPlayAnimIn
// 0x0008 (0x0008 - 0x0000)
struct WBP_Window_MachineOption_C_OnPlayAnimIn final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_OnPlayAnimIn;

// Function WBP_Window_MachineOption.WBP_Window_MachineOption_C.ExecuteUbergraph_WBP_Window_MachineOption
// 0x0018 (0x0018 - 0x0000)
struct WBP_Window_MachineOption_C_ExecuteUbergraph_WBP_Window_MachineOption final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Window_MachineOption_C_ExecuteUbergraph_WBP_Window_MachineOption;

}

